services:
  users-service:
    build:
      context: ./users_service
    container_name: users-service-${ENVIRONMENT:-prod}
    ports:
      - "${USERS_SERVICE_PORT:-8090}:8090"
    env_file:
      - ./users_service/.env
    restart: unless-stopped
    networks:
      - eras-network

networks:
  eras-network:
    external: false
