services:
  users-service:
    image: capitanpio/users-service:latest
    container_name: users_service
    ports:
      - "8090:8090"
    env_file:
      - .env          # create this file on the VPS with all required secrets
    restart: unless-stopped
